import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import java.io.IOException;
import java.nio.file.Paths;
import java.io.FileWriter;

/**
 * Entry point for the MiniBasic-to-Jasmin bytecode compiler.
 *
 * <p>This application performs the full compilation pipeline:</p>
 * <ol>
 *   <li>Reads a MiniBasic source file (or uses a default program)</li>
 *   <li>Lexes and parses the source into an AST</li>
 *   <li>Visits the AST via {@link JasminCodeGenerator} to produce Jasmin assembly</li>
 *   <li>Prints the symbol table and generated bytecodes</li>
 *   <li>Writes the Jasmin output to {@code output.j}</li>
 * </ol>
 *
 * <p>Usage: {@code java CompilerMain [source.bas]}</p>
 *
 * @author Asier Alamo, Sergio Alonso Zarcero, Andrea Pascual Aguilera
 */
public class CompilerMain {

    /**
     * Runs the MiniBasic compiler.
     *
     * @param args optional path to a {@code .bas} source file
     */
    public static void main(String[] args) {
        try {
            CharStream charStream;

            // 1. Read input source
            if (args.length > 0) {
                String filePath = args[0];
                System.out.println("Reading file: " + filePath);
                charStream = CharStreams.fromPath(Paths.get(filePath));
            } else {
                String defaultProgram = """
                    LET x = 10
                    LET y = "Hello"
                    PRINT x
                    PRINT y
                    """;
                System.out.println("No file provided. Using default program.");
                charStream = CharStreams.fromString(defaultProgram);
            }

            // 2. Create Lexer and Parser
            MiniBasicLexer lexer = new MiniBasicLexer(charStream);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            MiniBasicParser parser = new MiniBasicParser(tokens);

            // 3. Generate the Abstract Syntax Tree
            ParseTree tree = parser.prog();

            // 4. Run the code generator visitor
            JasminCodeGenerator generator = new JasminCodeGenerator();
            generator.visit(tree);

            // 5. Display the symbol table
            System.out.println("Symbol Table:");
            System.out.println(generator.getSymbolTable());

            // 6. Display the generated Jasmin code
            System.out.println("\nGenerated Jasmin Code:");
            System.out.println(generator.getJasminCode());

            System.out.println("\nGenerated Jasmin Code (subroutines):");
            System.out.println(generator.getJasminCodeSubroutine());

            // 7. Write Jasmin output to file
            try (FileWriter writer = new FileWriter("output.j")) {
                writer.write(generator.getJasminCode());
                writer.write(generator.getJasminCodeSubroutine());
                System.out.println("Jasmin code written to output.j");
            }

        } catch (IOException e) {
            System.err.println("I/O error: " + e.getMessage());
            e.printStackTrace();
        } catch (RecognitionException e) {
            System.err.println("Recognition error: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
